metadata:
  name: bd-deployment
spec:
  selector:
    matchLabels:
      app: bd
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: bd
    spec:
      containers:
      - name: bd
        image: codydearkland/bloggerdemo
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bd
  name: bd
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: bd
  type: LoadBalancer
